// Code generated by MockGen. DO NOT EDIT.
// Source: go.segfaultmedaddy.com/inertia/internal/inertiassr (interfaces: SsrClient)
//
// Generated by this command:
//
//	mockgen -destination ssr_mock.go -package inertiassr . SsrClient
//

// Package inertiassr is a generated GoMock package.
package inertiassr

import (
	context "context"
	reflect "reflect"

	inertiabase "go.segfaultmedaddy.com/inertia/internal/inertiabase"
	gomock "go.uber.org/mock/gomock"
)

// MockSsrClient is a mock of SsrClient interface.
type MockSsrClient struct {
	ctrl     *gomock.Controller
	recorder *MockSsrClientMockRecorder
	isgomock struct{}
}

// MockSsrClientMockRecorder is the mock recorder for MockSsrClient.
type MockSsrClientMockRecorder struct {
	mock *MockSsrClient
}

// NewMockSsrClient creates a new mock instance.
func NewMockSsrClient(ctrl *gomock.Controller) *MockSsrClient {
	mock := &MockSsrClient{ctrl: ctrl}
	mock.recorder = &MockSsrClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSsrClient) EXPECT() *MockSsrClientMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockSsrClient) Render(arg0 context.Context, arg1 *inertiabase.Page) (*SsrTemplateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", arg0, arg1)
	ret0, _ := ret[0].(*SsrTemplateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MockSsrClientMockRecorder) Render(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockSsrClient)(nil).Render), arg0, arg1)
}
