// Code generated by MockGen. DO NOT EDIT.
// Source: go.segfaultmedaddy.com/inertia/internal/inertiassr (interfaces: SSRClient)
//
// Generated by this command:
//
//	mockgen -destination ssr_mock.go -package inertiassr . SSRClient
//

// Package inertiassr is a generated GoMock package.
package inertiassr

import (
	context "context"
	reflect "reflect"

	inertiabase "go.segfaultmedaddy.com/inertia/internal/inertiabase"
	gomock "go.uber.org/mock/gomock"
)

// MockSSRClient is a mock of SSRClient interface.
type MockSSRClient struct {
	ctrl     *gomock.Controller
	recorder *MockSSRClientMockRecorder
	isgomock struct{}
}

// MockSSRClientMockRecorder is the mock recorder for MockSSRClient.
type MockSSRClientMockRecorder struct {
	mock *MockSSRClient
}

// NewMockSSRClient creates a new mock instance.
func NewMockSSRClient(ctrl *gomock.Controller) *MockSSRClient {
	mock := &MockSSRClient{ctrl: ctrl}
	mock.recorder = &MockSSRClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSRClient) EXPECT() *MockSSRClientMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockSSRClient) Render(arg0 context.Context, arg1 *inertiabase.Page) (*SSRTemplateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", arg0, arg1)
	ret0, _ := ret[0].(*SSRTemplateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MockSSRClientMockRecorder) Render(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render",
		reflect.TypeOf((*MockSSRClient)(nil).Render), arg0, arg1)
}
